openapi: 3.0.0
info:
  title: AI Chatbot API
  description: API for the AI-powered task management chatbot
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/{user_id}/chat:
    post:
      summary: Process a chat message and return a response
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user sending the message
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The message from the user
                  example: "Add a task to buy groceries"
                conversation_id:
                  type: string
                  description: Optional conversation ID to continue a conversation
                  example: "conv_abc123"
      responses:
        '200':
          description: Successful response from the AI assistant
          content:
            application/json:
              schema:
                type: object
                required:
                  - conversation_id
                  - response
                properties:
                  conversation_id:
                    type: string
                    description: The conversation ID (newly created or existing)
                    example: "conv_abc123"
                  response:
                    type: string
                    description: The response from the AI assistant
                    example: "I've added the task 'buy groceries'. You have 1 task now."
                  tool_calls:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: The name of the tool called
                          example: "add_task"
                        arguments:
                          type: object
                          description: Arguments passed to the tool
                          example:
                            title: "buy groceries"
                            description: ""
        '400':
          description: Bad request - invalid input
        '404':
          description: User not found
        '500':
          description: Internal server error

  /api/{user_id}/conversations:
    get:
      summary: Get a list of user's conversations
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conversation'
        '404':
          description: User not found

  /api/{user_id}/conversations/{conversation_id}:
    get:
      summary: Get messages from a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
        - name: conversation_id
          in: path
          required: true
          description: The ID of the conversation
          schema:
            type: string
      responses:
        '200':
          description: List of messages in the conversation
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
        '404':
          description: User or conversation not found

components:
  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the conversation
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated

    Message:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the message
        role:
          type: string
          enum: [user, assistant]
          description: Who sent the message
        content:
          type: string
          description: The content of the message
        created_at:
          type: string
          format: date-time
          description: When the message was created